T = {
"VALIDAÇÃO LOCAL DA MARIAH (DOCUMENTO MARIAH)":
"VALIDACIÓN LOCAL DE LA MARIAH (DOCUMENTO MARIAH)",
"Guia de Validação Local da MARIAH pelos Comitês de Ética em Pesquisa":
"Guía de Validación Local de la MARIAH por los Comités de Ética en Pesquisa",
"Quadro F.1  Guia de leitura da Validação Local (documento MARIAH)":
"Cuadro F.1  Guía de lectura de la Validación Local (documento MARIAH)",
"Esta Seção oferece um roteiro prático para Comitês de Ética em Pesquisa que decidam, por iniciativa institucional própria, validar a Matriz MARIAH na sua casuística. Não há plano nacional centralizado, não há adesão formal a consórcio, não há prazo de execução. Cada CEP roda o que lhe for útil, no ritmo que lhe couber. O retorno de resultados ao Grupo de Trabalho responsável pelo guia é facultativo e serve à evolução futura do instrumento. As três frentes propostas em F.2 (concordância entre avaliadores, distribuição empírica dos protocolos e convergência entre as duas versões da matriz) podem ser executadas em conjunto ou separadamente. A planilha-modelo que acompanha esta Seção automatiza o registro e o cálculo dos indicadores e dispensa o uso de qualquer software estatístico especializado.":
"Esta Sección ofrece un guion práctico para los Comités de Ética en Pesquisa que decidan, por iniciativa institucional propia, validar la Matriz MARIAH en su casuística. No hay un plan nacional centralizado, no hay adhesión formal a un consorcio, no hay plazo de ejecución. Cada CEP aplica lo que le resulte útil, al ritmo que le convenga. La devolución de resultados al Grupo de Trabajo responsable de la guía es facultativa y sirve a la evolución futura del instrumento. Los tres frentes propuestos en F.2 (concordancia entre evaluadores, distribución empírica de los protocolos y convergencia entre las dos versiones de la matriz) pueden ejecutarse en conjunto o por separado. La planilla-modelo que acompaña esta Sección automatiza el registro y el cálculo de los indicadores y prescinde de cualquier software estadístico especializado.",
"F.1  Por que validar a MARIAH na sua casuística":
"F.1  Por qué validar la MARIAH en su casuística",
"O Guia é explícito ao posicionar a MARIAH como instrumento de apoio à deliberação do Comitê de Ética em Pesquisa, e não como norma que vincule sua decisão. A adoção da matriz é escolha institucional de cada CEP. Esse mesmo espírito orienta a validação: nenhum CEP é obrigado a validar a MARIAH, e nenhum CEP precisa esperar decisão central para fazê-lo. Quando o colegiado entender que vale a pena verificar como a matriz se comporta nos protocolos que efetivamente lhe são submetidos, esta Seção de Validação Local oferece um roteiro prático para conduzir essa verificação.":
"La Guía es explícita al situar la MARIAH como instrumento de apoyo a la deliberación del Comité de Ética en Pesquisa, y no como norma que vincule su decisión. La adopción de la matriz es elección institucional de cada CEP. Ese mismo espíritu orienta la validación: ningún CEP está obligado a validar la MARIAH, y ningún CEP necesita esperar una decisión central para hacerlo. Cuando el colegiado entienda que vale la pena verificar cómo se comporta la matriz en los protocolos que efectivamente le son presentados, esta Sección de Validación Local ofrece un guion práctico para conducir esa verificación.",
"Há três razões pelas quais um CEP pode querer fazer essa validação. A primeira é o aprendizado institucional. A aplicação sistemática da matriz por dois ou mais membros do colegiado revela rapidamente quais perguntas estão sendo interpretadas de forma divergente, oferecendo insumo direto para a capacitação deliberativa descrita no documento MARIAH. A segunda é de qualificação institucional do parecer. Um CEP que demonstre, com base na sua própria casuística, que aplica a MARIAH de modo consistente entre avaliadores, fortalece a credibilidade dos seus pareceres em protocolos com inteligência artificial perante pesquisadores, patrocinadores e a sociedade. A terceira é de contribuição opcional à evolução do instrumento. Os pontos de corte atuais da Versão B são, conforme o próprio Guia reconhece, calibrações teóricas que ":
"Hay tres razones por las que un CEP puede querer realizar esta validación. La primera es el aprendizaje institucional. La aplicación sistemática de la matriz por dos o más miembros del colegiado revela rápidamente qué preguntas se están interpretando de forma divergente, lo que ofrece un insumo directo para la capacitación deliberativa descrita en el documento MARIAH. La segunda es la cualificación institucional del dictamen. Un CEP que demuestre, con base en su propia casuística, que aplica la MARIAH de modo consistente entre evaluadores, fortalece la credibilidad de sus dictámenes en protocolos con inteligencia artificial ante investigadores, patrocinadores y la sociedad. La tercera es la contribución opcional a la evolución del instrumento. Los puntos de corte actuales de la Versión B son, como la propia Guía reconoce, calibraciones teóricas que ",
"merecem ser testadas empiricamente. CEPs que queiram compartilhar suas observações com o Grupo de Trabalho responsável pelo guia podem fazê-lo pelo canal descrito em F.5.":
"merecen ser puestas a prueba empíricamente. Los CEPs que deseen compartir sus observaciones con el Grupo de Trabajo responsable de la guía pueden hacerlo por el canal descrito en F.5.",
"Vale, antes do roteiro, uma advertência. Esta Seção não pretende transformar membros de CEP em estatísticos. As métricas propostas em F.4 são as mínimas necessárias para que o colegiado leia os próprios resultados com segurança, e a planilha-modelo que acompanha esta Seção calcula essas métricas automaticamente. O que se espera do CEP é a deliberação colegiada sobre o que os números mostram, não o cálculo dos números em si.":
"Antes del guion, cabe una advertencia. Esta Sección no pretende convertir a los miembros del CEP en estadísticos. Las métricas propuestas en F.4 son las mínimas necesarias para que el colegiado lea sus propios resultados con seguridad, y la planilla-modelo que acompaña esta Sección calcula esas métricas automáticamente. Lo que se espera del CEP es la deliberación colegiada sobre lo que muestran los números, no el cálculo de los números en sí.",
"F.2  O que pode ser validado em três frentes":
"F.2  Qué puede validarse en tres frentes",
"Esta Seção propõe três frentes independentes de validação. Cada CEP pode rodar uma, duas ou as três, em qualquer ordem. As três compartilham a mesma unidade amostral: o protocolo de pesquisa com uso de inteligência artificial submetido ao CEP.":
"Esta Sección propone tres frentes independientes de validación. Cada CEP puede aplicar uno, dos o los tres, en cualquier orden. Los tres comparten la misma unidad muestral: el protocolo de investigación con uso de inteligencia artificial presentado al CEP.",
"F.2.1  Concordância entre avaliadores na Versão A":
"F.2.1  Concordancia entre evaluadores en la Versión A",
"A primeira frente verifica se dois ou mais integrantes do CEP, ao aplicarem a Versão A da MARIAH ao mesmo protocolo de forma independente, chegam à mesma classificação. É a frente operacionalmente mais simples e a que rende, do ponto de vista de aprendizado institucional, o retorno mais imediato. O colegiado descobre rapidamente em quais eixos há leitura convergente e em quais há discordância sistemática, o que orienta diretamente o que precisa ser conversado em reunião plenária.":
"El primer frente verifica si dos o más integrantes del CEP, al aplicar la Versión A de la MARIAH al mismo protocolo de forma independiente, llegan a la misma clasificación. Es el frente operativamente más sencillo y el que ofrece, desde el punto de vista del aprendizaje institucional, el retorno más inmediato. El colegiado descubre rápidamente en qué ejes hay una lectura convergente y en cuáles hay discordancia sistemática, lo que orienta directamente lo que debe conversarse en la reunión plenaria.",
"A recomendação é de pelo menos vinte protocolos avaliados em paralelo por dois membros do CEP, em condições de cegamento mútuo, antes de qualquer deliberação colegiada. Vinte é um piso prudente para que a estimativa de concordância tenha estabilidade mínima; CEPs com volume maior de protocolos com IA podem ampliar essa marca sem prejuízo, e CEPs com volume menor podem ir acumulando avaliações ao longo do tempo, sem prazo, até atingir essa marca.":
"La recomendación es de al menos veinte protocolos evaluados en paralelo por dos miembros del CEP, en condiciones de cegamiento mutuo, antes de cualquier deliberación colegiada. Veinte es un piso prudente para que la estimación de concordancia tenga una estabilidad mínima; los CEPs con mayor volumen de protocolos con IA pueden ampliar esa cifra sin perjuicio, y los CEPs con menor volumen pueden ir acumulando evaluaciones a lo largo del tiempo, sin plazo, hasta alcanzarla.",
"F.2.2  Distribuição empírica dos protocolos nos quatro níveis":
"F.2.2  Distribución empírica de los protocolos en los cuatro niveles",
"A segunda frente examina como os protocolos avaliados pelo CEP se distribuem nos quatro níveis da MARIAH. Há dois usos principais para essa informação. O primeiro é descritivo. O CEP passa a conhecer o perfil da sua casuística em pesquisa com inteligência artificial: se a maioria dos protocolos se concentra no Nível II, se há protocolos no Nível IV, se a distribuição mudou ao longo do tempo. Essa informação é insumo de planejamento institucional e de capacitação do colegiado. O segundo uso é diagnóstico. Quando a distribuição se concentra perto de um ponto de corte da ":
"El segundo frente examina cómo se distribuyen los protocolos evaluados por el CEP en los cuatro niveles de la MARIAH. Hay dos usos principales para esa información. El primero es descriptivo. El CEP pasa a conocer el perfil de su casuística en investigación con inteligencia artificial: si la mayoría de los protocolos se concentra en el Nivel II, si hay protocolos en el Nivel IV, si la distribución cambió a lo largo del tiempo. Esa información es insumo de planificación institucional y de capacitación del colegiado. El segundo uso es diagnóstico. Cuando la distribución se concentra cerca de un punto de corte de la ",
"Versão B, o colegiado tem evidência local de que pequenas variações na pontuação podem deslocar muitos protocolos de nível, o que justifica examinar com mais atenção os casos limítrofes.":
"Versión B, el colegiado tiene evidencia local de que pequeñas variaciones en la puntuación pueden cambiar de nivel muchos protocolos, lo que justifica examinar con más atención los casos limítrofes.",
"A recomendação operacional é registrar a pontuação total e a pontuação por bloco de todos os protocolos aos quais o CEP aplicar a Versão B, sem critério de inclusão específico. A planilha-modelo produz automaticamente o histograma e identifica concentrações próximas aos pontos de corte.":
"La recomendación operativa es registrar la puntuación total y la puntuación por bloque de todos los protocolos a los que el CEP aplique la Versión B, sin criterio de inclusión específico. La planilla-modelo produce automáticamente el histograma e identifica concentraciones próximas a los puntos de corte.",
"F.2.3  Convergência entre Versões A e B no modo triagem":
"F.2.3  Convergencia entre las Versiones A y B en el modo triaje",
"A terceira frente examina se a Versão A e a Versão B, aplicadas ao mesmo protocolo no modo triagem previsto pelo Guia, convergem para a mesma classificação de risco. Quando o CEP usa rotineiramente o modo triagem (Versão A como filtro inicial e Versão B em casos de Nível III ou Nível IV) basta registrar as duas classificações em paralelo. Discordâncias sistemáticas entre as duas versões, quando ocorrem, são informação valiosa: ou indicam que o CEP está lendo de modo inconsistente as duas versões, ou indicam que as duas versões captam dimensões diferentes do risco no protocolo. Em ambos os casos, o colegiado tem material concreto para discutir e, se for o caso, reportar ao Grupo de Trabalho.":
"El tercer frente examina si la Versión A y la Versión B, aplicadas al mismo protocolo en el modo triaje previsto por la Guía, convergen en la misma clasificación de riesgo. Cuando el CEP usa rutinariamente el modo triaje (Versión A como filtro inicial y Versión B en casos de Nivel III o Nivel IV), basta con registrar las dos clasificaciones en paralelo. Las discordancias sistemáticas entre las dos versiones, cuando ocurren, son información valiosa: o indican que el CEP está leyendo de modo inconsistente las dos versiones, o indican que las dos versiones captan dimensiones diferentes del riesgo en el protocolo. En ambos casos, el colegiado tiene material concreto para discutir y, si corresponde, informar al Grupo de Trabajo.",
"F.3  Como conduzir cada frente":
"F.3  Cómo conducir cada frente",
"O roteiro a seguir cobre as três frentes em um único fluxo. Cada CEP adapta o fluxo à sua dinâmica.":
"El guion que sigue cubre los tres frentes en un único flujo. Cada CEP adapta el flujo a su dinámica.",
"O primeiro passo é definir o período de coleta. Pode ser um trimestre, um semestre ou aberto. O importante é o CEP saber que, durante esse período, os protocolos com inteligência artificial recebidos serão objeto também do exercício de validação, em paralelo ao parecer ordinário. A coleta não altera o fluxo do parecer institucional do SINEP.":
"El primer paso es definir el período de recolección. Puede ser un trimestre, un semestre o abierto. Lo importante es que el CEP sepa que, durante ese período, los protocolos con inteligencia artificial recibidos también serán objeto del ejercicio de validación, en paralelo al dictamen ordinario. La recolección no altera el flujo del dictamen institucional del SINEP.",
"O segundo passo é constituir a dupla ou trio de avaliadores. A recomendação é que pelo menos dois membros do colegiado apliquem a Versão A de forma independente, sem consulta prévia entre si, e que um terceiro membro aplique a Versão B em separado. Avaliadores podem se revezar a cada protocolo; o que importa é a independência da aplicação dentro de cada protocolo. Não é necessário que o avaliador da Versão B seja o relator do parecer institucional.":
"El segundo paso es constituir la dupla o el trío de evaluadores. La recomendación es que al menos dos miembros del colegiado apliquen la Versión A de forma independiente, sin consulta previa entre sí, y que un tercer miembro aplique la Versión B por separado. Los evaluadores pueden turnarse en cada protocolo; lo que importa es la independencia de la aplicación dentro de cada protocolo. No es necesario que el evaluador de la Versión B sea el relator del dictamen institucional.",
"O terceiro passo é registrar as avaliações na planilha-modelo. A planilha tem aba específica para cada frente. Cada protocolo recebe um identificador interno do CEP que dispensa qualquer ":
"El tercer paso es registrar las evaluaciones en la planilla-modelo. La planilla tiene una pestaña específica para cada frente. Cada protocolo recibe un identificador interno del CEP que prescinde de cualquier ",
"informação que permita identificar pesquisador, instituição proponente ou patrocinador. A planilha não pede esses dados. O registro mínimo é o identificador, a data e as respostas dos avaliadores nas perguntas da matriz. As fórmulas calculam a classificação consolidada, a pontuação total e os indicadores agregados das três frentes.":
"información que permita identificar al investigador, a la institución proponente o al patrocinador. La planilla no solicita esos datos. El registro mínimo es el identificador, la fecha y las respuestas de los evaluadores a las preguntas de la matriz. Las fórmulas calculan la clasificación consolidada, la puntuación total y los indicadores agregados de los tres frentes.",
"O quarto passo é a deliberação colegiada sobre os achados. Recomenda-se reunião dedicada, ao final do período de coleta ou periodicamente durante ele, para que o colegiado discuta o que os indicadores estão mostrando. A planilha gera um painel-resumo que apoia essa discussão. A deliberação é o ponto central do exercício; os números são insumo, não conclusão.":
"El cuarto paso es la deliberación colegiada sobre los hallazgos. Se recomienda una reunión dedicada, al final del período de recolección o periódicamente durante él, para que el colegiado discuta lo que los indicadores están mostrando. La planilla genera un panel-resumen que apoya esa discusión. La deliberación es el punto central del ejercicio; los números son insumo, no conclusión.",
"F.4  Como interpretar os achados":
"F.4  Cómo interpretar los hallazgos",
"A interpretação dos achados não exige conhecimento estatístico avançado. Para as três frentes propostas, três leituras básicas bastam.":
"La interpretación de los hallazgos no exige conocimiento estadístico avanzado. Para los tres frentes propuestos, bastan tres lecturas básicas.",
"Para a frente de concordância entre avaliadores, o indicador principal é a estatística kappa de Cohen, calculada automaticamente pela planilha. A Tabela F.1 oferece a leitura prática dos valores observados. O colegiado lê o valor de kappa por eixo da Versão A e por classificação consolidada, identifica os eixos com kappa baixo e discute, em plenária, os casos de discordância naqueles eixos.":
"Para el frente de concordancia entre evaluadores, el indicador principal es el estadístico kappa de Cohen, calculado automáticamente por la planilla. La Tabla F.1 ofrece la lectura práctica de los valores observados. El colegiado lee el valor de kappa por eje de la Versión A y por clasificación consolidada, identifica los ejes con kappa bajo y discute, en plenaria, los casos de discordancia en esos ejes.",
"Tabela F.1  Leitura prática dos valores de kappa":
"Tabla F.1  Lectura práctica de los valores de kappa",
"Valor de kappa": "Valor de kappa",
"Leitura prática": "Lectura práctica",
"Abaixo de 0,40": "Por debajo de 0,40",
"Concordância insuficiente. O eixo ou bloco merece revisão pelo colegiado: as perguntas estão sendo lidas de modo divergente, e isso é informação valiosa para discutir em plenária.":
"Concordancia insuficiente. El eje o bloque merece revisión por el colegiado: las preguntas se están leyendo de modo divergente, y eso es información valiosa para discutir en plenaria.",
"Entre 0,40 e 0,60": "Entre 0,40 y 0,60",
"Concordância moderada. Identifique os casos de discordância e use-os como pauta de reunião, porque são exatamente os casos limítrofes que o Guia trata ao abordar a formação dos comitês.":
"Concordancia moderada. Identifique los casos de discordancia y úselos como orden del día de la reunión, porque son exactamente los casos limítrofes que la Guía trata al abordar la formación de los comités.",
"Entre 0,60 e 0,80": "Entre 0,60 y 0,80",
"Concordância substancial. A aplicação está consistente. Pequenas discordâncias residuais são esperadas e saudáveis.":
"Concordancia sustancial. La aplicación es consistente. Pequeñas discordancias residuales son esperables y saludables.",
"0,80 ou acima": "0,80 o más",
"Concordância quase perfeita. A aplicação está estabilizada. Cuidado, porém: kappas muito altos em todos os eixos podem indicar que os avaliadores estão deliberando entre si antes de registrar as respostas, o que esvazia o exercício.":
"Concordancia casi perfecta. La aplicación está estabilizada. Cuidado, sin embargo: kappas muy altos en todos los ejes pueden indicar que los evaluadores están deliberando entre sí antes de registrar las respuestas, lo que vacía el ejercicio.",
"Fonte: Adaptado de Landis e Koch (1977).":
"Fuente: adaptado de Landis y Koch (1977).",
"Para a frente de distribuição empírica, a leitura é visual. O colegiado analisa o histograma da planilha para verificar a concentração de protocolos em algum nível, a proximidade com os pontos de corte e a presença de bimodalidade (dois picos separados por um vale). Concentração próxima aos pontos de corte é alerta de que pequenas variações na aplicação da matriz produzem mudanças de nível. Bimodalidade marcada é evidência local de que o ponto de corte natural na casuística do CEP pode diferir do ponto teórico vigente.":
"Para el frente de distribución empírica, la lectura es visual. El colegiado analiza el histograma de la planilla para verificar la concentración de protocolos en algún nivel, la proximidad a los puntos de corte y la presencia de bimodalidad (dos picos separados por un valle). La concentración cerca de los puntos de corte es una alerta de que pequeñas variaciones en la aplicación de la matriz producen cambios de nivel. Una bimodalidad marcada es evidencia local de que el punto de corte natural en la casuística del CEP puede diferir del punto teórico vigente.",
"A leitura é tabular para a frente de convergência entre versões. A planilha gera uma tabela de contingência quatro por quatro que cruza as classificações da Versão A e da Versão B no modo triagem.  Alta convergência ocorre quando a diagonal principal concentra mais de oitenta por cento dos protocolos.  Padrões de discordância, que exigem exame qualitativo dos protocolos correspondentes, surgem quando há concentração em pares específicos fora da diagonal, como Nível II na Versão A e Nível III na Versão B.":
"Para el frente de convergencia entre versiones, la lectura es tabular. La planilla genera una tabla de contingencia de cuatro por cuatro que cruza las clasificaciones de la Versión A y de la Versión B en el modo triaje.  Hay alta convergencia cuando la diagonal principal concentra más del ochenta por ciento de los protocolos.  Los patrones de discordancia, que exigen un examen cualitativo de los protocolos correspondientes, surgen cuando hay concentración en pares específicos fuera de la diagonal, como Nivel II en la Versión A y Nivel III en la Versión B.",
"A planilha não impõe interpretação ao colegiado. Os indicadores são apresentados com leitura sugerida, mas a deliberação sobre o que fazer com eles é decisão institucional do CEP.":
"La planilla no impone interpretación al colegiado. Los indicadores se presentan con una lectura sugerida, pero la deliberación sobre qué hacer con ellos es decisión institucional del CEP.",
"F.5  Quando e como compartilhar resultados com o Grupo de Trabalho":
"F.5  Cuándo y cómo compartir resultados con el Grupo de Trabajo",
"CEPs que decidirem compartilhar suas observações com o Grupo de Trabalho responsável pelo guia podem fazê-lo a qualquer momento por meio da Secretaria Executiva da INAEP (se.inaep@saude.gov.br). Não há prazo, não há formulário obrigatório, não há contrapartida institucional. O compartilhamento é ato voluntário, e seu único propósito é informar a evolução futura do instrumento.":
"Los CEPs que decidan compartir sus observaciones con el Grupo de Trabajo responsable de la guía pueden hacerlo en cualquier momento a través de la Secretaría Ejecutiva de la INAEP (se.inaep@saude.gov.br). No hay plazo, no hay formulario obligatorio, no hay contrapartida institucional. Compartir es un acto voluntario, y su único propósito es informar la evolución futura del instrumento.",
"O canal sugerido é o envio da planilha-modelo, preenchida e com identificação institucional do CEP, para o endereço eletrônico do Grupo de Trabalho indicado na página oficial do guia. O envio pode ser feito em qualquer formato que o CEP preferir: a planilha completa, um resumo dos indicadores agregados ou apenas uma nota narrativa descrevendo o que o colegiado observou. CEPs que tenham preocupação com a confidencialidade de informações institucionais podem encaminhar apenas os indicadores agregados, sem os registros por protocolo.":
"El canal sugerido es el envío de la planilla-modelo, cumplimentada y con la identificación institucional del CEP, a la dirección electrónica del Grupo de Trabajo indicada en la página oficial de la guía. El envío puede hacerse en el formato que el CEP prefiera: la planilla completa, un resumen de los indicadores agregados o solo una nota narrativa que describa lo que el colegiado observó. Los CEPs preocupados por la confidencialidad de la información institucional pueden enviar solo los indicadores agregados, sin los registros por protocolo.",
"O Grupo de Trabalho consolidará as contribuições recebidas e as utilizará, em conjunto com outras fontes de evidência, para informar eventuais revisões da matriz em ciclos futuros de atualização do guia. As contribuições não terão atribuição nominal sem autorização expressa do CEP remetente, e nenhum CEP será identificado em publicação derivada sem seu consentimento institucional.":
"El Grupo de Trabajo consolidará las contribuciones recibidas y las utilizará, junto con otras fuentes de evidencia, para informar eventuales revisiones de la matriz en ciclos futuros de actualización de la guía. Las contribuciones no tendrán atribución nominal sin autorización expresa del CEP remitente, y ningún CEP será identificado en una publicación derivada sin su consentimiento institucional.",
"F.6  Recursos disponíveis":
"F.6  Recursos disponibles",
"Acompanha esta Seção uma planilha-modelo em formato .xlsx, com abas dedicadas a cada uma das três frentes de validação, fórmulas pré-configuradas para cálculo dos indicadores e painel-resumo com leitura sugerida. A planilha pode ser usada em qualquer software compatível, como Microsoft Excel, LibreOffice Calc ou Google Sheets, e não requer instalação de qualquer extensão estatística.":
"Acompaña esta Sección una planilla-modelo en formato .xlsx, con pestañas dedicadas a cada uno de los tres frentes de validación, fórmulas preconfiguradas para el cálculo de los indicadores y un panel-resumen con lectura sugerida. La planilla puede usarse en cualquier software compatible, como Microsoft Excel, LibreOffice Calc o Google Sheets, y no requiere instalar ninguna extensión estadística.",
"O software MARIAH, descrito no Guia e disponibilizado como Software Público Brasileiro, oferece uma camada operacional complementar: a aplicação das matrizes diretamente em formato digital, com exportação de relatórios padronizados. CEPs que prefiram operar o exercício de validação em ambiente digital podem fazê-lo exportando os relatórios e transferindo os dados para a planilha-modelo desta Seção de Validação Local. O repositório oficial do software fica em github.com/Tonaco-13.":
"El software MARIAH, descrito en la Guía y puesto a disposición como Software Público Brasileño, ofrece una capa operativa complementaria: la aplicación de las matrices directamente en formato digital, con exportación de informes estandarizados. Los CEPs que prefieran realizar el ejercicio de validación en un entorno digital pueden hacerlo exportando los informes y transfiriendo los datos a la planilla-modelo de esta Sección de Validación Local. El repositorio oficial del software está en github.com/Tonaco-13.",
"Dúvidas operacionais sobre a aplicação deste roteiro podem ser encaminhadas, junto com observações e sugestões, pelo canal indicado em F.5.":
"Las dudas operativas sobre la aplicación de este guion pueden enviarse, junto con observaciones y sugerencias, por el canal indicado en F.5.",
"Referências": "Referencias",
# Referências bibliográficas: mantidas no original (norma de citação)
"BRASIL. Conselho Nacional de Saúde. Resolução n.º 466, de 12 de dezembro de 2012. Brasília: Ministério da Saúde, 2012.": None,
"BRASIL. Conselho Nacional de Saúde. Resolução n.º 510, de 7 de abril de 2016. Brasília: Ministério da Saúde, 2016.": None,
"BRASIL. Conselho Nacional de Saúde. Resolução n.º 738, de 8 de novembro de 2024. Brasília: Ministério da Saúde, 2024.": None,
"COHEN, J. A coefficient of agreement for nominal scales. Educational and Psychological Measurement, v. 20, n. 1, p. 37–46, 1960.": None,
"LANDIS, J. R.; KOCH, G. G. The measurement of observer agreement for categorical data. Biometrics, v. 33, n. 1, p. 159–174, 1977.": None,
"SAMUELS, R.; OLIVEIRA, A. S. (Org.). Diretrizes éticas para pesquisa com inteligência artificial: guia para Comitês de Ética em Pesquisa. Brasília: Ministério da Saúde, no prelo. Capítulos 7 e 9.": None,
"Guia de Uso Ético de Inteligência Artificial em Pesquisa com Seres Humanos  ·  Validação Local (documento MARIAH)":
"Guía de Uso Ético de la Inteligencia Artificial en Investigación con Seres Humanos  ·  Validación Local (documento MARIAH)",
"Página ": "Página ",
"1": None,
}
